import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Materiostock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-blue-400 flex flex-col items-center justify-center h-screen ">
        <img
          src="https://materiostock-front-ks.vercel.app/static/logo_white_horizontal.svg"
          alt="logo"
          className="max-w-44 w-80"
        />

        <p className="text-white mt-8">Site prochainement accessible</p>
      </main>
    </div>
  );
}
